controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

alumno_editar:
    path: /editar/{id}
    controller: App\Controller\AlumnoController::editarAlumno

